---
title: "regression trees matching"
author: "Yandong Xiong"
date: "2021/3/31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## import needed packages
```{r}
require(MatchIt)
require(dplyr)
require(ggplot2)
require(Hmisc)
require(rpart)
require(partykit)
require(RItools)
require(glmnet)
```

## import datasets
```{r}
data.l = read.csv("../data/lowDim_dataset.csv") %>% mutate(A = as.factor(A))
data.h = read.csv("../data/highDim_dataset.csv") %>% mutate(A = as.factor(A))
head(data.l)
head(data.h)
```

## paring 8 on lowDim data
```{r}
set.seed(2020)

model_tm.l = system.time(tree <- rpart(A~., data = data.l[,-1], method = "class")) + 
system.time(min_cp <-tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]) +
system.time(tree_prune <- prune(tree, cp=min_cp))

ps_tm.l = system.time(ps <- predict(tree_prune, data.l[,-1], type = "prob")[,2])

treat_ps = cbind(1:500, data.l[,"A"],ps)
colnames(treat_ps) = c("index", "treatOrNot", "propensityScore")
#head(treat_ps,100)
ps.dt = as_tibble(treat_ps)
treated = ps.dt %>% filter(treatOrNot == 2)
(treated_score = unique(treated$propensityScore))
notTreated = ps.dt %>% filter(treatOrNot == 1)
(notTreated_score = unique(notTreated$propensityScore))
#discarded = as.matrix(ps.dt[1,])
matched_t = as.matrix(ps.dt[1,])
matched_nt = as.matrix(ps.dt[1,])
matched_score = treated_score[sort(treated_score) == sort(notTreated_score)]
matching_tm.l = 0
for (i in 1:length(matched_score)) {
  matching_tm.l = matching_tm.l +
    system.time(matched_t <- rbind(matched_t, treated%>%filter(propensityScore==matched_score[i]))) +
    system.time(matched_nt <- rbind(matched_nt, notTreated%>%filter(propensityScore==matched_score[i])))
}
matched_t = matched_t[-1,]
matched_nt = matched_nt[-1,]
matched_dt = data.l[sort(c(matched_t$index,matched_nt$index)),]
dim(matched_dt)
head(matched_dt,50)
Y.1 = data.l[matched_t$index,]$Y
Y.0 = data.l[matched_nt$index,]$Y
ATE_tm.l = system.time(ATE.l <- mean(Y.1) - mean(Y.0))
list(model_tm.l[1], ps_tm.l[1], matching_tm.l[1], ATE_tm.l[1])
ATE.l
```
# paring 8 on highDim data
```{r}
set.seed(2021)

model_tm.h = system.time(tree <- rpart(A~., data = data.h[,-1], method = "class")) + 
system.time(min_cp <-tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]) +
system.time(tree_prune <- prune(tree, cp=min_cp))

ps_tm.h = system.time(ps <- predict(tree_prune, data.h[,-1], type = "prob")[,2])

treat_ps = cbind(1:500, data.h[,"A"],ps)
colnames(treat_ps) = c("index", "treatOrNot", "propensityScore")
#head(treat_ps,100)
ps.dt = as_tibble(treat_ps)
treated = ps.dt %>% filter(treatOrNot == 2)
(treated_score = unique(treated$propensityScore))
notTreated = ps.dt %>% filter(treatOrNot == 1)
(notTreated_score = unique(notTreated$propensityScore))
discarded = as.matrix(ps.dt[1,])
matched_t = as.matrix(ps.dt[1,])
matched_nt = as.matrix(ps.dt[1,])
matched_score = treated_score[sort(treated_score) == sort(notTreated_score)]
matching_tm.h = 0
for (i in 1:length(matched_score)) {
  matching_tm.h = matching_tm.h +
    system.time(matched_t <- rbind(matched_t, treated%>%filter(propensityScore==matched_score[i]))) +
    system.time(matched_nt <- rbind(matched_nt, notTreated%>%filter(propensityScore==matched_score[i])))
}
matched_t = matched_t[-1,]
matched_nt = matched_nt[-1,]
matched_dt = data.h[sort(c(matched_t$index,matched_nt$index)),]
dim(matched_dt)
head(matched_dt,50)
Y.1 = data.h[matched_t$index,]$Y
Y.0 = data.h[matched_nt$index,]$Y
ATE_tm.h = system.time(ATE.h <- mean(Y.1) - mean(Y.0))
list(model_tm.h[1], ps_tm.h[1], matching_tm.h[1], ATE_tm.h[1])
ATE.h
```


# paring 24 on lowDim data
```{r}
set.seed(2020)
x = model.matrix(A~.,data.l[,-1])[,-1]
y = data.l[,2]
cv.lasso <- cv.glmnet(x, y, alpha = 1, family = "binomial")
fit_lasso = glmnet(x, y, family = "binomial", alpha = 1, lambda = cv.lasso$lambda.min)

ps = predict(fit_lasso, x, type="response")
ps.dt = as_tibble(ps) %>% mutate(index = 1:length(ps), treatedOrNot = data.l$A) %>% rename(ps="s0")
w = (as.numeric(ps.dt$treatedOrNot)-1)/ps.dt$ps + (2-as.numeric(ps.dt$treatedOrNot))/(1-ps.dt$ps)
var.indicator = summary(lm(Y~., data=data.l))$coefficients[,4]<.05

z = model.matrix(A~.,data.l[,-1])[,var.indicator[-2]][,-1]
zMinusZBar = matrix(nrow = dim(z)[1],ncol = dim(z)[2])
for (i in 1:dim(z)[2]) {
  zMinusZBar[,i] = (z[,i] - colMeans(z)[i])*(as.numeric(y)[i]-1)
}
colnames(zMinusZBar) = sapply(colnames(zMinusZBar), function(x) paste(x,paste(x,"_bar",sep=""),sep="-"))
(ATE.l = lm(Y~.,data = cbind(data.l[,1:2], z, zMinusZBar), weights = w)$coefficients[2])
```

# paring 24 on highDim data
```{r}
set.seed(2020)
x = model.matrix(A~.,data.h[,-1])[,-1]
y = data.h[,2]
cv.lasso <- cv.glmnet(x, y, alpha = 1, family = "binomial")
fit_lasso = glmnet(x, y, family = "binomial", alpha = 1, lambda = cv.lasso$lambda.min)

ps = predict(fit_lasso, s = cv.lasso$lambda.min, newx = x)
ps.dt = as_tibble(ps) %>% mutate(index = 1:length(ps), treatedOrNot = data.h$A) %>% rename(ps="1")
w = (as.numeric(ps.dt$treatedOrNot)-1)/ps.dt$ps + (2-as.numeric(ps.dt$treatedOrNot))/(1-ps.dt$ps)

ps = predict(fit_lasso, x, type="response")
ps.dt = as_tibble(ps) %>% mutate(index = 1:length(ps), treatedOrNot = data.h$A) %>% rename(ps="s0")
w = (as.numeric(ps.dt$treatedOrNot)-1)/ps.dt$ps + (2-as.numeric(ps.dt$treatedOrNot))/(1-ps.dt$ps)
var.indicator = summary(lm(Y~., data=data.h))$coefficients[,4]<.05

z = model.matrix(A~.,data.h[,-1])[,var.indicator[-2]][,-1]
zMinusZBar = matrix(nrow = dim(z)[1],ncol = dim(z)[2])
for (i in 1:dim(z)[2]) {
  zMinusZBar[,i] = (z[,i] - colMeans(z)[i])*(as.numeric(y)[i]-1)
}
colnames(zMinusZBar) = sapply(colnames(zMinusZBar), function(x) paste(x,paste(x,"_bar",sep=""),sep="-"))
(ATE.l = lm(Y~.,data = cbind(data.h[,1:2], z, zMinusZBar), weights = w)$coefficients[2])
```